# Generated by Django 2.0.4 on 2026-09-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_chat', models.BigIntegerField()),
                ('vk_id', models.BigIntegerField(null=True)),
                ('tg_chat', models.BigIntegerField()),
                ('tg_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('buttons', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(default=None, max_length=256, null=True)),
                ('username', models.CharField(default=None, max_length=256, null=True)),
                ('status', models.IntegerField(choices=[(-1, 'Заблокирован'), (0, 'Базовый')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VkChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('is_polling', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TgUser')),
            ],
        ),
        migrations.AddField(
            model_name='forward',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TgUser'),
        ),
        migrations.AddField(
            model_name='forward',
            name='tgchat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TgChat'),
        ),
        migrations.AddField(
            model_name='forward',
            name='vkchat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.VkChat'),
        ),
        migrations.AddIndex(
            model_name='vkuser',
            index=models.Index(fields=['token', 'is_polling'], name='idx_token_polling'),
        ),
    ]