# Generated by Django 2.1.15 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_action_code', models.CharField(blank=True, max_length=8, null=True)),
                ('manual_action_timestamp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]